version: "3.7"

services:
  #App service
  app:
    container_name: "finstat-app"
    image: finstat-app:0.0.1
    restart: always
    ports:
      - "8080:8080"
      - "1349:1349"
    depends_on:
      - postgres
      - migrate

  #Migrate
  migrate:
    image: migrate/migrate:latest
    container_name: "finstat-app-migrate"
    restart: on-failure
    volumes:
      - ../migrations:/migrations
    entrypoint: ""
    command: [ "sh", "-c", "sleep 3 && migrate -path /migrations -database postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable up" ]
    depends_on:
      - postgres

  #DB
  postgres:
    container_name: "postgres-finstat"
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    volumes:
      - ../postgres-data:/var/lib/postgres/data
